POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John",
    "number": 7834124698
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 7834124698
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John"
}